### ISSUE TITLE
Not working on Android 4.4.4 as of 1/10/2015

### ISSUE THREAD

**Issue by genewitch** [strassl/Lampshade#7]
Pages never load (tropes, random, from chrome)

let me know here if there's any other information i can provide!

**Comment by sli** [comment]
This is due to the new layout changing a few things that Lampshade relies on. Namely:

    <td id="wikibody">

has been replaced with

    <div class="main Main">

Line 146 in `TropesArticle.java` needs to updated to reflect this. Maybe other stuff, too, but this is the first I found.

**Comment by genewitch** [comment]
oh, I noticed the main site looked different. How do i edit the TropesArticle.java on my phone to fix; or are you planning a patch in the future?

**Comment by sli** [comment]
I took a bit to peruse some parts of then source earlier. I plan on issuing a pull request sometime this week, because I want a distraction from school.

**Comment by genewitch** [comment]
okay thank you so much! I use lampshade for like an hour every day -or more!

**Comment by genewitch** [comment]
strassl <3

**Comment by bergamote** [comment]
I still get "page couldn't load". I installed via fdroid so it's version 1.1.7. I take it that's normal.

**Comment by strassl** [comment]
I don't know who decided to package Lampshade for f-droid, but apparently it is horribly out of date. Current version is 1.3.3, which contains some serious improvements over 1.1.7.
An update should hopefully fix your issues. The application is available on the Play Store, but if you do not have access to it either build it yourself or just shoot me a mail and I'll send you the current apk. :)

**Comment by bergamote** [comment]
Fdroid now has 1.3.4, so it works perfectly!
